version: "3.9"

services:
  wp:
    image: wordpress:latest
    container_name: wordpress
    volumes:
      - $PWD/plugins/:/var/www/html/wp-content/plugins/my-plugin
      - wp_data:/var/www/html    
    networks: 
      - contnet
    ports:
      - '8080:80'
    restart: always
    environment: 
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${WP_USER}
      WORDPRESS_DB_PASSWORD: ${DBUSER_PASSWORD}
      WORDPRESS_DB_NAME: ${WP_DATABASE}
  
  db:
    image: mysql
    volumes:
       - mysql:/var/lib/mysql
    restart: always
    networks: 
      - contnet
    ports:
      - '3306:3306'
    environment: 
      MYSQL_DATABASE: ${WP_DATABASE}
      MYSQL_USER: ${WP_USER}
      MYSQL_PASSWORD: ${DBUSER_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
    #command: '--default-authentication-plugin=mysql_native_password' 
  
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - '8081:80'
    networks:
      - contnet
    environment:
      PMA_HOSTS: db
    ### uncomment for the two row below for AUTOLOGIN ###
    # PMA_USER:{MYSQL_USER} 
    # PMA_PASSWORD: {MYSQL_PASSWORD}
  
  portainer:
    image: portainer/portainer-ce:2.9.3
    restart: always
    ports:
      - '9443:9443'
      - '8000:8000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data


volumes:
  mysql:
  src:
  plugins:
  wp_data:
  portainer:


networks:
  contnet:
    driver: bridge


