version: '3.3'

services:
  wp-site01:
    depends_on: 
      - db
    image: wordpress
    container_name: site01
    volumes:
      - ./wp-docker/var/www/html/wp-content/plugins/meu-plugin
    ports: 
      - "8081:80"    
    networks: 
      - contnet
    restart: always
    environment: 
      MYSQL_DB_HOST: db:3306
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_DB_USER: ${MYSQL_USER}
      MYSQL_DB_PASSWORD: ${MYSQL_PASSWORD}
  
  db:
    image: mysql:5.7
    volumes:
      - db:/var/lib/mysql
    networks: 
      - contnet
    ports:
      - "3306:3306"  
    environment: 
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_DB_USER: ${MYSQL_USER}
      MYSQL_DB_PASSWORD: ${MYSQL_PASSWORD}  
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  adminer:
    depends_on: 
      - db
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - contnet
volumes:
  db: {}   
networks:
  contnet:
    driver: bridge


