version: "3.9"

services:
  wp_s01:
    env_file:
      - connection.env
    build:
      dockerfile: ./wp.dockerfile
      context: .
    image: douglascristiann/wp_site:1.0
    container_name: site01
    # volumes:
    #   - src:/var/www/html/wp-content/plugins/meu-plugin
    #   - ./wp_data:/var/www/html    
    networks: 
      - contnet
    restart: always
    environment: 
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
  
  db:
    env_file:
      - connection.env
    build:
      dockerfile: ./dbmysql.dockerfile
      context: .
    container_name: wp_mysql
    image: douglascristiann/dbmysql:5.7
    # volumes:
    #   - db:/var/lib/mysql
    restart: always
    networks: 
      - contnet
    environment: 
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: '1' 

# volumes:  
#   db: {}
#   wp_data: {}
#   src: {}   

networks:
  contnet:
    driver: bridge


